---
- name: Add nginx logrotate dependent config
  ansible.builtin.set_fact:
    logrotate__dependent_config: >-
      {{
        (logrotate__dependent_config | default([]))
        + nginx_logrotate__dependent_config
      }}
  # noqa: var-naming
