---
- name: Add imapsync logrotate dependent config
  ansible.builtin.set_fact:
    logrotate__dependent_config: >-
      {{
        (logrotate__dependent_config | default([]))
        + imapsync__logrotate__dependent_config
      }}
  # noqa: var-naming
