---
# @meta author:value: [Amedee Van Gasse](https://amedee.be)
galaxy_info:
  description: Role to configure imapsync.
  author: Amedee Van Gasse
  license: MIT
  min_ansible_version: "2.1"
  namespace: amedee
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies:
  - role: debops.debops.cron
  - role: debops.debops.logrotate
