---
# @meta author:value: [Amedee Van Gasse](https://amedee.be)
galaxy_info:
  description: Wrapper role to configure etckeeper.
  author: Amedee Van Gasse
  license: MIT
  min_ansible_version: "2.1"
  namespace: amedee
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies:
  - role: debops.debops.etckeeper
    vars:
      etckeeper__enabled: true
      etckeeper__vcs: git
      etckeeper__vcs_user: root
      etckeeper__vcs_email: "root@{{ ansible_hostname }}"
